version: "3"

services:
  errbit_rails:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - PORT=8080
      - RACK_ENV=production
      - MONGO_URL=mongodb://mongo:27017/errbit
  mongo:
    image: mongo:3.4.4
    ports:
      - "27017:27017"
    expose:
      - "27017"
